on:
  push:
    branches: 
      - 20.05
    pull_request:
        branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quai.io/galaxy/covid-19-training:20.05